// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/wangn-tech/tiny-douyin/internal/api/handler"
	"github.com/wangn-tech/tiny-douyin/internal/dao"
	"github.com/wangn-tech/tiny-douyin/internal/global"
	"github.com/wangn-tech/tiny-douyin/internal/pkg/upload"
	"github.com/wangn-tech/tiny-douyin/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitUserHandler 初始化 UserHandler（Wire 自动生成实现）
func InitUserHandler() *handler.UserHandler {
	db := ProvideDB()
	iUserDAO := dao.NewUserDAO(db)
	iUserService := service.NewUserService(iUserDAO)
	userHandler := handler.NewUserHandler(iUserService)
	return userHandler
}

// InitVideoHandler 初始化 VideoHandler（Wire 自动生成实现）
func InitVideoHandler() *handler.VideoHandler {
	db := ProvideDB()
	iVideoDAO := dao.NewVideoDAO(db)
	iUserDAO := dao.NewUserDAO(db)
	iVideoService := service.NewVideoService(iVideoDAO, iUserDAO)
	iUploadService := upload.NewUploadService()
	videoHandler := handler.NewVideoHandler(iVideoService, iUploadService)
	return videoHandler
}

// InitUploadWorker 初始化 UploadWorker（Wire 自动生成实现）
func InitUploadWorker() upload.IUploadWorker {
	iUploadService := upload.NewUploadService()
	db := ProvideDB()
	iVideoDAO := dao.NewVideoDAO(db)
	iUploadWorker := upload.NewWorker(iUploadService, iVideoDAO)
	return iUploadWorker
}

// wire.go:

// ProvideDB 提供数据库连接
func ProvideDB() *gorm.DB {
	return global.DB
}

// UploadSet Upload 层 Provider Set
var UploadSet = wire.NewSet(upload.NewUploadService, upload.NewWorker)

// DAOSet DAO 层 Provider Set（只注入 DB）
var DAOSet = wire.NewSet(dao.NewUserDAO, dao.NewVideoDAO)

// ServiceSet Service 层 Provider Set（只注入 DAO）
var ServiceSet = wire.NewSet(service.NewUserService, service.NewVideoService, DAOSet)

// HandlerSet Handler 层 Provider Set（只注入 Service 和 Upload）
var HandlerSet = wire.NewSet(handler.NewUserHandler, handler.NewVideoHandler, ServiceSet,
	UploadSet,
)
