// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/wangn-tech/tiny-douyin/internal/api/handler"
	"github.com/wangn-tech/tiny-douyin/internal/dao"
	"github.com/wangn-tech/tiny-douyin/internal/global"
	"github.com/wangn-tech/tiny-douyin/internal/pkg/upload"
	"github.com/wangn-tech/tiny-douyin/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitUserHandler 初始化 UserHandler（Wire 自动生成实现）
func InitUserHandler() *handler.UserHandler {
	db := ProvideDB()
	iUserDAO := dao.NewUserDAO(db)
	iUserService := service.NewUserService(iUserDAO)
	userHandler := handler.NewUserHandler(iUserService)
	return userHandler
}

// InitVideoHandler 初始化 VideoHandler（Wire 自动生成实现）
func InitVideoHandler() *handler.VideoHandler {
	db := ProvideDB()
	iVideoDAO := dao.NewVideoDAO(db)
	iUserDAO := dao.NewUserDAO(db)
	iFavoriteDAO := dao.NewFavoriteDAO(db)
	iVideoService := service.NewVideoService(iVideoDAO, iUserDAO, iFavoriteDAO)
	iUploadService := upload.NewUploadService()
	videoHandler := handler.NewVideoHandler(iVideoService, iUploadService)
	return videoHandler
}

// InitUploadWorker 初始化 UploadWorker（Wire 自动生成实现）
func InitUploadWorker() upload.IUploadWorker {
	iUploadService := upload.NewUploadService()
	db := ProvideDB()
	iVideoDAO := dao.NewVideoDAO(db)
	iUploadWorker := upload.NewWorker(iUploadService, iVideoDAO)
	return iUploadWorker
}

// InitFavoriteHandler 初始化 FavoriteHandler（Wire 自动生成实现）
func InitFavoriteHandler() *handler.FavoriteHandler {
	db := ProvideDB()
	iFavoriteDAO := dao.NewFavoriteDAO(db)
	iVideoDAO := dao.NewVideoDAO(db)
	iUserDAO := dao.NewUserDAO(db)
	iFavoriteService := service.NewFavoriteService(iFavoriteDAO, iVideoDAO, iUserDAO)
	favoriteHandler := handler.NewFavoriteHandler(iFavoriteService)
	return favoriteHandler
}

// InitCommentHandler 初始化 CommentHandler（Wire 自动生成实现）
func InitCommentHandler() *handler.CommentHandler {
	db := ProvideDB()
	iCommentDAO := dao.NewCommentDAO(db)
	iVideoDAO := dao.NewVideoDAO(db)
	iUserDAO := dao.NewUserDAO(db)
	iCommentService := service.NewCommentService(iCommentDAO, iVideoDAO, iUserDAO, db)
	commentHandler := handler.NewCommentHandler(iCommentService)
	return commentHandler
}

// wire.go:

// ProvideDB 提供数据库连接
func ProvideDB() *gorm.DB {
	return global.DB
}

// UploadSet Upload 层 Provider Set
var UploadSet = wire.NewSet(upload.NewUploadService, upload.NewWorker)

// DAOSet DAO 层 Provider Set（只注入 DB）
var DAOSet = wire.NewSet(dao.NewUserDAO, dao.NewVideoDAO, dao.NewFavoriteDAO, dao.NewCommentDAO)

// ServiceSet Service 层 Provider Set（只注入 DAO）
var ServiceSet = wire.NewSet(service.NewUserService, service.NewVideoService, service.NewFavoriteService, service.NewCommentService, DAOSet)

// HandlerSet Handler 层 Provider Set（只注入 Service 和 Upload）
var HandlerSet = wire.NewSet(handler.NewUserHandler, handler.NewVideoHandler, handler.NewFavoriteHandler, handler.NewCommentHandler, ServiceSet,
	UploadSet,
)
